//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderCandidate
    {
        public int OrderCandidateID { get; set; }
        public Nullable<int> StoreID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<bool> IsAvailable { get; set; }
        public string Price { get; set; }
        public string CreatedOn { get; set; }
        public string UpdatedOn { get; set; }
        public Nullable<int> RecieptOrderID { get; set; }
    }
}
