//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int ProductID { get; set; }
        public string Name { get; set; }
        public string Quantity { get; set; }
        public string AddedOn { get; set; }
        public string UpdatedOn { get; set; }
        public Nullable<int> RecieptID { get; set; }
        public Nullable<bool> IsAvailable { get; set; }
        public string Price { get; set; }
    
        public virtual Reciept Reciept { get; set; }
    }
}
