//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecieptOrder
    {
        public int RecieptOrderID { get; set; }
        public Nullable<int> RecieptID { get; set; }
        public Nullable<int> SenderStoreID { get; set; }
        public string OrderTime { get; set; }
        public Nullable<int> ReceiverStoreID { get; set; }
        public string Subtotal { get; set; }
        public Nullable<bool> AssignedStatus { get; set; }
    }
}
