//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reciept
    {
        public Reciept()
        {
            this.Products = new HashSet<Product>();
        }
    
        public int RecieptID { get; set; }
        public string Name { get; set; }
        public Nullable<int> StoreID { get; set; }
        public string CreatedOn { get; set; }
        public string Status { get; set; }
        public string Price { get; set; }
    
        public virtual ICollection<Product> Products { get; set; }
        public virtual StoreUser StoreUser { get; set; }
    }
}
