//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoreUser
    {
        public StoreUser()
        {
            this.Reciepts = new HashSet<Reciept>();
        }
    
        public int StoreUserID { get; set; }
        public string StoreName { get; set; }
        public string Username { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string DeviceID { get; set; }
        public Nullable<bool> Active { get; set; }
        public string DeviceType { get; set; }
    
        public virtual ICollection<Reciept> Reciepts { get; set; }
    }
}
